### ISSUE TITLE
Jetpack4.4.1

### ISSUE THREAD

**Issue by unca121** [forecr/forecr_xavier_kernel#1]
Hi,
could you please share flashing manual? Because I can't get DSBOARD_XV2 for AGX Xavier working.

I tried copying of /arch/arm64/boot/Image with /arch/arm64/boot/dts/ from kernel_out as mentioned at [NVidia docs](https://docs.nvidia.com/jetson/l4t/index.html#page/Tegra%20Linux%20Driver%20Package%20Development%20Guide/kernel_custom.html#wwpID0E0WD0HA)

Thank you

**Comment by mdeniz0** [comment]
We are preparing xavier & nano kernel blog posts. We will share it with you as soon as possible.

At this point, if you want to compile the kernel source now, you can follow these steps below to resolve your issue quickly:

> #Load Environment
> $ cd ./kernel/kernel-4.9/
> $ source ../../environment_nvidia
> 
> #DSBOARD_XV2 for AGX Xavier compile
> $ make ARCH=arm64 O=$HOME/kernel_out_dsboard_xv2 dsboard_xv2_defconfig
> $ make ARCH=arm64 O=$HOME/kernel_out_dsboard_xv2 -j$(($(nproc)-1))
> 
> #Copy the compiled files to the Jetson HW image folder (change the dtb file as tegra194-p2888-0001-p2822-0000.dtb)
> $ cp $HOME/kernel_out_dsboard_xv2/arch/arm64/boot/Image $HOME/nvidia/nvidia_sdk/JetPack_4.4.1_Linux_JETSON_AGX_XAVIER/Linux_for_Tegra/kernel/Image
> $ cp $HOME/kernel_out_dsboard_xv2/arch/arm64/boot/dts/tegra194-p2888-0001-dsboard-xv2-0000.dtb $HOME/nvidia/nvidia_sdk/JetPack_4.4.1_Linux_JETSON_AGX_XAVIER/Linux_for_Tegra/kernel/dtb/tegra194-p2888-0001-p2822-0000.dtb
> 

Additionally, you can find the precompiled binaries from [here](https://github.com/mistelektronik/dsboard_xv2_agx_xavier_bsp/blob/master/agx_xavier_JP4_4_1_bsp.zip).

Kind Regards

**Comment by mdeniz0** [comment]
Hello @unca121 

We have recently published the Xavier kernel-source building blog post. The blog post is for JetPack-4.6 but it can be applied to other versions as well.
You can follow this link below:

https://www.forecr.io/blogs/bsp-development/how-to-compile-forecr-xavier-kernel
