### ISSUE TITLE
Support for JetPack 6.0 DP

### ISSUE THREAD

**Issue by TeaBear5** [forecr/forecr_xavier_kernel#2]
Do you have any plan to support Jetson Linux 36.2  / Jetpack 6.0?

**Comment by mdeniz0** [comment]
Hello @TeaBear5,

Yes, we will deploy JetPack-6 based kernel sources in this repository. The following products will contain JetPack-6.0 DP support:
- DSBOARD-AGX
- DSBOARD-AGXMAX
- MILBOARD-AGX
- RAIBOX-ORNX
- DSBOARD-ORNX
- DSBOARD-ORNX-LAN and 
- DSBOARD-ORNXS

Now, we are still implementing these products in it. Once we complete our tests, we will publish ASAP.
